openapi: 3.0.3
info:
  title: goal
  version: 0.0.1
  description: |
    goal-api

paths:
  '/goals/{goal_id}/asset-management-plan':
    parameters:
      - $ref: '../afs-client.yaml#/components/parameters/GoalId'
    get:
      summary: 顧客のゴール詳細。
      description: |
        顧客のゴール詳細を返却する。
      tags:
        - ゴール
      operationId: get-goals-goal-id-asset-management-plan
      security:
        - Branch/Fa: []
      responses:
        '200':
          description: |
            顧客のゴール詳細。
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AssetManagementPlanDetailResponse'
              examples:
                運用プラン（据置）見直し中（revised）が存在する場合:
                  value:
                    goal_type: 'donation'
                    made:
                      plan_type: 'deferral'
                      name: '寄付がしたいから'
                      goal_amount: 23000000
                      calculated_goal_amount: 23000000
                      achievement_probability: 88
                      future_return:
                        - percentile: 88
                          data: [12, 12, 13]
                        - percentile: 90
                          data: [13, 14, 15]
                        - percentile: 50
                          data: [10, 11, 12]
                        - percentile: 10
                          data: [9, 10, 11]
                      future_estimation:
                        - percentile: 68
                          data: [13, 14, 15]
                        - percentile: 50
                          data: [10, 11, 12]
                        - percentile: 32
                          data: [9, 10, 11]
                      asset_management_result: [7, 8, 9, 10]
                      reserve_total_amount: null
                      withdrawal_total_amount: null
                      starts_at: '2020-04-01T00:00:00.000Z'
                      completed_at: '2024-05-06T00:00:00.000Z'
                      created_at: '2021-06-01T00:00:00.000Z'
                      initial_investment: 4000000
                      asset_management_period_years: 30
                      asset_management_period_months: 0
                      risk_level: 3
                      application_fa_name: 田中 太郎
                      application_date: 2020-04-01T00:00:00.000Z
                      funds_source: '預貯金'
                      percentage_in_financial_assets_over: 30
                      percentage_in_financial_assets_under: 50
                      fluctuation_funds_type: increase
                      fluctuation_funds_amount: 120000
                      spot_invest_date: '2022-09-08'
                      part_cancel_invest_date: null
                      fund_url: 'https://www.multi-tenant.co.jp/fund/funddetail.php?t=2&fundcd=180361#fundinfo'
                      current_price: 103000
                      first_achievement_probability: 78
                      contract_method: 'pdf_contract'
                      application_status: 'waiting_for_application'
                    revised:
                      plan_type: 'deferral'
                      name: '寄付がしたいから'
                      goal_amount: 23000000
                      calculated_goal_amount: 23000000
                      achievement_probability: 88
                      future_return:
                        - percentile: 88
                          data: [12, 12, 13]
                        - percentile: 90
                          data: [13, 14, 15]
                        - percentile: 50
                          data: [10, 11, 12]
                        - percentile: 10
                          data: [9, 10, 11]
                      future_estimation:
                        - percentile: 68
                          data: [13, 14, 15]
                        - percentile: 50
                          data: [10, 11, 12]
                        - percentile: 32
                          data: [9, 10, 11]
                      asset_management_result: [7, 8, 9, 10]
                      reserve_total_amount: null
                      withdrawal_total_amount: null
                      starts_at: '2020-04-01T00:00:00.000Z'
                      completed_at: '2024-05-06T00:00:00.000Z'
                      created_at: '2021-06-01T00:00:00.000Z'
                      initial_investment: 4000000
                      asset_management_period_years: 30
                      asset_management_period_months: 0
                      reserve_start_year: null
                      reserve_start_month: null
                      reserve_period_years: null
                      reserve_period_months: null
                      withdrawal_start_year: null
                      withdrawal_start_month: null
                      withdrawal_period_years: null
                      withdrawal_period_months: null
                      withdrawal_frequency: null
                      withdrawal_amount: null
                      increased_amount_at_bonus: null
                      reserve_monthly_amount: null
                      bonus_months: []
                      risk_level: 3
                      application_fa_name: 田中 太郎
                      application_date: 2020-04-01T00:00:00.000Z
                      funds_source: '預貯金'
                      percentage_in_financial_assets_over: 30
                      percentage_in_financial_assets_under: 50
                      fluctuation_funds_type: null
                      fluctuation_funds_amount: null
                      spot_invest_date: null
                      part_cancel_invest_date: null
                    contract_status: 'on_contract_application'
                    invalid_application_reason: 口座開設不備
                    contract_class: 6
                    new_nisa: '2'
                    current_price_detail:
                      current_price_sum: null
                運用プラン（据置）（revised）が存在しない場合:
                  value:
                    goal_type: 'donation'
                    made:
                      plan_type: 'deferral'
                      name: '寄付がしたいから'
                      goal_amount: 23000000
                      calculated_goal_amount: 23000000
                      achievement_probability: 88
                      future_return:
                        - percentile: 88
                          data: [12, 12, 13]
                        - percentile: 90
                          data: [13, 14, 15]
                        - percentile: 50
                          data: [10, 11, 12]
                        - percentile: 10
                          data: [9, 10, 11]
                      future_estimation:
                        - percentile: 68
                          data: [13, 14, 15]
                        - percentile: 50
                          data: [10, 11, 12]
                        - percentile: 32
                          data: [9, 10, 11]
                      asset_management_result: [7, 8, 9, 10]
                      reserve_total_amount: null
                      withdrawal_total_amount: null
                      starts_at: '2020-04-01T00:00:00.000Z'
                      completed_at: '2024-05-06T00:00:00.000Z'
                      created_at: '2021-06-01T00:00:00.000Z'
                      initial_investment: 4000000
                      asset_management_period_years: 30
                      asset_management_period_months: 0
                      risk_level: 3
                      application_fa_name: 田中 太郎
                      application_date: 2020-04-01T00:00:00.000Z
                      funds_source: '預貯金'
                      percentage_in_financial_assets_over: 30
                      percentage_in_financial_assets_under: 50
                      fluctuation_funds_type: null
                      fluctuation_funds_amount: null
                      spot_invest_date: null
                      part_cancel_invest_date: null
                      fund_url: 'https://www.multi-tenant.co.jp/fund/funddetail.php?t=2&fundcd=180361#fundinfo'
                      current_price: 103000
                      first_achievement_probability: 78
                      contract_method: 'pdf_contract'
                      application_status: 'waiting_for_application'
                    revised: null
                    contract_status: 'on_contract_application'
                    invalid_application_reason: null
                    contract_class: 1
                    new_nisa: '2'
                    current_price_detail:
                      current_price_sum: 30000
                      nisa_amount: null
                      taxable_amount: null
                運用プラン（積立）（revised）が存在する場合:
                  value:
                    goal_type: 'donation'
                    made:
                      plan_type: 'reserve'
                      name: '寄付がしたいから'
                      goal_amount: 23000000
                      calculated_goal_amount: 23000000
                      achievement_probability: 88
                      future_return:
                        - percentile: 88
                          data: [12, 12, 13]
                        - percentile: 90
                          data: [13, 14, 15]
                        - percentile: 50
                          data: [10, 11, 12]
                        - percentile: 10
                          data: [9, 10, 11]
                      future_estimation:
                        - percentile: 68
                          data: [13, 14, 15]
                        - percentile: 50
                          data: [10, 11, 12]
                        - percentile: 32
                          data: [9, 10, 11]
                      asset_management_result: [7, 8, 9, 10]
                      reserve_total_amount: 100000
                      withdrawal_total_amount: null
                      starts_at: '2020-04-01T00:00:00.000Z'
                      completed_at: '2024-05-06T00:00:00.000Z'
                      created_at: '2021-06-01T00:00:00.000Z'
                      initial_investment: 4000000
                      asset_management_period_years: 30
                      asset_management_period_months: 0
                      reserve_start_year: 2021
                      reserve_start_month: 8
                      reserve_period_years: 25
                      reserve_period_months: 0
                      risk_level: 3
                      application_fa_name: 田中 太郎
                      application_date: 2020-04-01T00:00:00.000Z
                      funds_source: '預貯金'
                      percentage_in_financial_assets_over: 30
                      percentage_in_financial_assets_under: 50
                      reserve_monthly_amount: null
                      bonus_months: []
                      increased_amount_at_bonus: null
                      fluctuation_funds_type: increase
                      fluctuation_funds_amount: 120000
                      spot_invest_date: '2022-09-08'
                      part_cancel_invest_date: null
                      fund_url: 'https://www.multi-tenant.co.jp/fund/funddetail.php?t=2&fundcd=180361#fundinfo'
                      current_price: 103000
                      first_achievement_probability: 78
                      contract_method: 'pdf_contract'
                      application_status: 'waiting_for_application'
                    revised:
                      plan_type: 'reserve'
                      name: '寄付がしたいから'
                      goal_amount: 23000000
                      calculated_goal_amount: 23000000
                      achievement_probability: 88
                      future_return:
                        - percentile: 88
                          data: [12, 12, 13]
                        - percentile: 90
                          data: [13, 14, 15]
                        - percentile: 50
                          data: [10, 11, 12]
                        - percentile: 10
                          data: [9, 10, 11]
                      future_estimation:
                        - percentile: 68
                          data: [13, 14, 15]
                        - percentile: 50
                          data: [10, 11, 12]
                        - percentile: 32
                          data: [9, 10, 11]
                      asset_management_result: [7, 8, 9, 10]
                      reserve_total_amount: 100000
                      withdrawal_total_amount: null
                      starts_at: '2020-04-01T00:00:00.000Z'
                      completed_at: '2024-05-06T00:00:00.000Z'
                      created_at: '2021-06-01T00:00:00.000Z'
                      initial_investment: 4000000
                      asset_management_period_years: 30
                      asset_management_period_months: 0
                      reserve_start_year: 2021
                      reserve_start_month: 8
                      reserve_period_years: 25
                      reserve_period_months: 0
                      withdrawal_start_year: null
                      withdrawal_start_month: null
                      withdrawal_period_years: null
                      withdrawal_period_months: null
                      withdrawal_frequency: null
                      withdrawal_amount: null
                      risk_level: 3
                      application_fa_name: 田中 太郎
                      application_date: 2020-04-01T00:00:00.000Z
                      funds_source: '預貯金'
                      percentage_in_financial_assets_over: 30
                      percentage_in_financial_assets_under: 50
                      reserve_monthly_amount: null
                      bonus_months: []
                      increased_amount_at_bonus: null
                      fluctuation_funds_type: null
                      fluctuation_funds_amount: null
                    contract_status: 'on_contract_application'
                    invalid_application_reason: 口座開設不備
                    contract_class: 6
                    new_nisa: '2'
                    current_price_detail:
                      current_price_sum: null
                運用プラン（積立）（revised）が存在しない場合:
                  value:
                    goal_type: 'donation'
                    made:
                      plan_type: 'reserve'
                      name: '寄付がしたいから'
                      goal_amount: 23000000
                      calculated_goal_amount: 23000000
                      achievement_probability: 88
                      future_return:
                        - percentile: 88
                          data: [12, 12, 13]
                        - percentile: 90
                          data: [13, 14, 15]
                        - percentile: 50
                          data: [10, 11, 12]
                        - percentile: 10
                          data: [9, 10, 11]
                      future_estimation:
                        - percentile: 68
                          data: [13, 14, 15]
                        - percentile: 50
                          data: [10, 11, 12]
                        - percentile: 32
                          data: [9, 10, 11]
                      asset_management_result: [7, 8, 9, 10]
                      reserve_total_amount: 100000
                      withdrawal_total_amount: null
                      starts_at: '2020-04-01T00:00:00.000Z'
                      completed_at: '2024-05-06T00:00:00.000Z'
                      created_at: '2021-06-01T00:00:00.000Z'
                      initial_investment: 4000000
                      asset_management_period_years: 30
                      asset_management_period_months: 0
                      reserve_start_year: 2021
                      reserve_start_month: 8
                      reserve_period_years: 25
                      reserve_period_months: 0
                      risk_level: 3
                      application_fa_name: 田中 太郎
                      application_date: 2020-04-01T00:00:00.000Z
                      funds_source: '預貯金'
                      percentage_in_financial_assets_over: 30
                      percentage_in_financial_assets_under: 50
                      reserve_monthly_amount: null
                      bonus_months: []
                      increased_amount_at_bonus: null
                      fluctuation_funds_type: null
                      fluctuation_funds_amount: null
                      spot_invest_date: null
                      part_cancel_invest_date: null
                      fund_url: 'https://www.multi-tenant.co.jp/fund/funddetail.php?t=2&fundcd=180361#fundinfo'
                      current_price: 103000
                      first_achievement_probability: 78
                      contract_method: 'pdf_contract'
                      application_status: 'waiting_for_application'
                    revised: null
                    contract_status: 'on_contract_application'
                    invalid_application_reason: null
                    contract_class: 1
                    new_nisa: '2'
                    current_price_detail:
                      current_price_sum: 30000
                      nisa_amount: null
                      taxable_amount: null
                運用プラン（据置・引出）（revised）が存在する場合:
                  value:
                    goal_type: 'donation'
                    made:
                      plan_type: 'deferral_withdrawal'
                      name: '寄付がしたいから'
                      goal_amount: 23000000
                      calculated_goal_amount: 23000000
                      achievement_probability: 88
                      future_return:
                        - percentile: 88
                          data: [12, 12, 13]
                        - percentile: 90
                          data: [13, 14, 15]
                        - percentile: 50
                          data: [10, 11, 12]
                        - percentile: 10
                          data: [9, 10, 11]
                      future_estimation:
                        - percentile: 68
                          data: [13, 14, 15]
                        - percentile: 50
                          data: [10, 11, 12]
                        - percentile: 32
                          data: [9, 10, 11]
                      asset_management_result: [7, 8, 9, 10]
                      reserve_total_amount: null
                      withdrawal_total_amount: 100000
                      starts_at: '2020-04-01T00:00:00.000Z'
                      completed_at: '2024-05-06T00:00:00.000Z'
                      created_at: '2021-06-01T00:00:00.000Z'
                      initial_investment: 4000000
                      asset_management_period_years: 30
                      asset_management_period_months: 0
                      reserve_start_year: null
                      reserve_start_month: null
                      reserve_period_years: null
                      reserve_period_months: null
                      bonus_months: []
                      increased_amount_at_bonus: null
                      withdrawal_start_year: 2037
                      withdrawal_start_month: 6
                      withdrawal_period_years: 20
                      withdrawal_period_months: 0
                      withdrawal_frequency: 'monthly'
                      withdrawal_amount: 360000
                      risk_level: 3
                      application_fa_name: 田中 太郎
                      application_date: 2020-04-01T00:00:00.000Z
                      funds_source: '預貯金'
                      percentage_in_financial_assets_over: 30
                      percentage_in_financial_assets_under: 50
                      fluctuation_funds_type: increase
                      fluctuation_funds_amount: 120000
                      spot_invest_date: '2022-09-08'
                      part_cancel_invest_date: null
                      fund_url: 'https://www.multi-tenant.co.jp/fund/funddetail.php?t=2&fundcd=180361#fundinfo'
                      current_price: 103000
                      first_achievement_probability: 78
                      contract_method: 'pdf_contract'
                      application_status: 'waiting_for_application'
                    revised:
                      plan_type: 'deferral_withdrawal'
                      name: '寄付がしたいから'
                      goal_amount: 23000000
                      achievement_probability: 88
                      future_return:
                        - percentile: 88
                          data: [12, 12, 13]
                        - percentile: 90
                          data: [13, 14, 15]
                        - percentile: 50
                          data: [10, 11, 12]
                        - percentile: 10
                          data: [9, 10, 11]
                      future_estimation:
                        - percentile: 68
                          data: [13, 14, 15]
                        - percentile: 50
                          data: [10, 11, 12]
                        - percentile: 32
                          data: [9, 10, 11]
                      asset_management_result: [7, 8, 9, 10]
                      reserve_total_amount: null
                      withdrawal_total_amount: 100000
                      starts_at: '2020-04-01T00:00:00.000Z'
                      completed_at: '2024-05-06T00:00:00.000Z'
                      created_at: '2021-06-01T00:00:00.000Z'
                      initial_investment: 4000000
                      withdrawal_start_year: 2037
                      withdrawal_start_month: 6
                      withdrawal_period_years: 20
                      withdrawal_period_months: 0
                      withdrawal_frequency: 'monthly'
                      withdrawal_amount: 360000
                      risk_level: 3
                      application_fa_name: 田中 太郎
                      application_date: 2020-04-01T00:00:00.000Z
                      funds_source: '預貯金'
                      percentage_in_financial_assets_over: 30
                      percentage_in_financial_assets_under: 50
                      fluctuation_funds_type: null
                      fluctuation_funds_amount: null
                      spot_invest_date: null
                      part_cancel_invest_date: null
                    contract_status: 'on_contract_application'
                    invalid_application_reason: 口座開設不備
                    contract_class: 6
                    new_nisa: '2'
                    current_price_detail:
                      current_price_sum: null
                運用プラン（据置・引出）（revised）が存在しない場合:
                  value:
                    goal_type: 'donation'
                    made:
                      plan_type: 'deferral_withdrawal'
                      name: '寄付がしたいから'
                      goal_amount: 23000000
                      calculated_goal_amount: 23000000
                      achievement_probability: 88
                      future_return:
                        - percentile: 88
                          data: [12, 12, 13]
                        - percentile: 90
                          data: [13, 14, 15]
                        - percentile: 50
                          data: [10, 11, 12]
                        - percentile: 10
                          data: [9, 10, 11]
                      future_estimation:
                        - percentile: 68
                          data: [13, 14, 15]
                        - percentile: 50
                          data: [10, 11, 12]
                        - percentile: 32
                          data: [9, 10, 11]
                      asset_management_result: [7, 8, 9, 10]
                      reserve_total_amount: null
                      withdrawal_total_amount: 100000
                      starts_at: '2020-04-01T00:00:00.000Z'
                      completed_at: '2024-05-06T00:00:00.000Z'
                      created_at: '2021-06-01T00:00:00.000Z'
                      initial_investment: 4000000
                      asset_management_period_years: 30
                      asset_management_period_months: 0
                      withdrawal_start_year: 2037
                      withdrawal_start_month: 6
                      withdrawal_period_years: 20
                      withdrawal_period_months: 0
                      withdrawal_frequency: 'monthly'
                      withdrawal_amount: 360000
                      risk_level: 3
                      application_fa_name: 田中 太郎
                      application_date: 2020-04-01T00:00:00.000Z
                      funds_source: '預貯金'
                      percentage_in_financial_assets_over: 30
                      percentage_in_financial_assets_under: 50
                      fluctuation_funds_type: null
                      fluctuation_funds_amount: null
                      spot_invest_date: null
                      part_cancel_invest_date: null
                      fund_url: 'https://www.multi-tenant.co.jp/fund/funddetail.php?t=2&fundcd=180361#fundinfo'
                      current_price: 103000
                      first_achievement_probability: 78
                      contract_method: 'pdf_contract'
                      application_status: 'waiting_for_application'
                    revised: null
                    contract_status: 'on_contract_application'
                    invalid_application_reason: null
                    contract_class: 1
                    new_nisa: '1'
                    current_price_detail:
                      current_price_sum: 30000
                      nisa_amount: 10000
                      taxable_amount: 20000
                運用プラン（積立・据置・引出）（revised）が存在する場合:
                  value:
                    goal_type: 'donation'
                    made:
                      plan_type: 'reserve_deferral_withdrawal'
                      name: '寄付がしたいから'
                      goal_amount: 23000000
                      calculated_goal_amount: 23000000
                      achievement_probability: 88
                      future_return:
                        - percentile: 88
                          data: [12, 12, 13]
                        - percentile: 90
                          data: [13, 14, 15]
                        - percentile: 50
                          data: [10, 11, 12]
                        - percentile: 10
                          data: [9, 10, 11]
                      future_estimation:
                        - percentile: 68
                          data: [13, 14, 15]
                        - percentile: 50
                          data: [10, 11, 12]
                        - percentile: 32
                          data: [9, 10, 11]
                      asset_management_result: [7, 8, 9, 10]
                      reserve_total_amount: 100000
                      withdrawal_total_amount: 100000
                      starts_at: '2020-04-01T00:00:00.000Z'
                      completed_at: '2024-05-06T00:00:00.000Z'
                      created_at: '2021-06-01T00:00:00.000Z'
                      asset_management_period_years: 30
                      asset_management_period_months: 0
                      initial_investment: 4000000
                      reserve_start_year: 2021
                      reserve_start_month: 8
                      reserve_period_years: 25
                      reserve_period_months: 0
                      withdrawal_start_year: 2037
                      withdrawal_start_month: 6
                      withdrawal_period_years: 20
                      withdrawal_period_months: 0
                      withdrawal_frequency: 'monthly'
                      withdrawal_amount: 360000
                      risk_level: 3
                      application_fa_name: 田中 太郎
                      application_date: 2020-04-01T00:00:00.000Z
                      funds_source: '預貯金'
                      percentage_in_financial_assets_over: 30
                      percentage_in_financial_assets_under: 50
                      reserve_monthly_amount: null
                      bonus_months: []
                      increased_amount_at_bonus: null
                      fluctuation_funds_type: increase
                      fluctuation_funds_amount: 120000
                      spot_invest_date: '2022-09-08'
                      part_cancel_invest_date: null
                      fund_url: 'https://www.multi-tenant.co.jp/fund/funddetail.php?t=2&fundcd=180361#fundinfo'
                      current_price: 103000
                      first_achievement_probability: 78
                      contract_method: 'pdf_contract'
                      application_status: 'waiting_for_application'
                    revised:
                      plan_type: 'reserve_deferral_withdrawal'
                      name: '寄付がしたいから'
                      goal_amount: 23000000
                      calculated_goal_amount: 23000000
                      achievement_probability: 88
                      future_return:
                        - percentile: 88
                          data: [12, 12, 13]
                        - percentile: 90
                          data: [13, 14, 15]
                        - percentile: 50
                          data: [10, 11, 12]
                        - percentile: 10
                          data: [9, 10, 11]
                      future_estimation:
                        - percentile: 68
                          data: [13, 14, 15]
                        - percentile: 50
                          data: [10, 11, 12]
                        - percentile: 32
                          data: [9, 10, 11]
                      asset_management_result: [7, 8, 9, 10]
                      reserve_total_amount: 100000
                      withdrawal_total_amount: 100000
                      starts_at: '2020-04-01T00:00:00.000Z'
                      completed_at: '2024-05-06T00:00:00.000Z'
                      created_at: '2021-06-01T00:00:00.000Z'
                      initial_investment: 4000000
                      asset_management_period_years: null
                      asset_management_period_months: null
                      reserve_start_year: 2021
                      reserve_start_month: 8
                      reserve_period_years: 25
                      reserve_period_months: 0
                      withdrawal_start_year: 2037
                      withdrawal_start_month: 6
                      withdrawal_period_years: 20
                      withdrawal_period_months: 0
                      withdrawal_frequency: 'monthly'
                      withdrawal_amount: 360000
                      risk_level: 3
                      application_fa_name: 田中 太郎
                      application_date: 2020-04-01T00:00:00.000Z
                      funds_source: '預貯金'
                      percentage_in_financial_assets_over: 30
                      percentage_in_financial_assets_under: 50
                      reserve_monthly_amount: null
                      bonus_months: []
                      increased_amount_at_bonus: null
                      fluctuation_funds_type: null
                      fluctuation_funds_amount: null
                      spot_invest_date: null
                      part_cancel_invest_date: null
                    contract_status: 'on_contract_application'
                    invalid_application_reason: 口座開設不備
                    contract_class: 6
                    new_nisa: '2'
                    current_price_detail:
                      current_price_sum: null
                運用プラン（積立・据置・引出）（revised）が存在しない場合:
                  value:
                    goal_type: 'donation'
                    made:
                      plan_type: 'reserve_deferral_withdrawal'
                      name: '寄付がしたいから'
                      goal_amount: 23000000
                      calculated_goal_amount: 23000000
                      achievement_probability: 88
                      future_return:
                        - percentile: 88
                          data: [12, 12, 13]
                        - percentile: 90
                          data: [13, 14, 15]
                        - percentile: 50
                          data: [10, 11, 12]
                        - percentile: 10
                          data: [9, 10, 11]
                      future_estimation:
                        - percentile: 68
                          data: [13, 14, 15]
                        - percentile: 50
                          data: [10, 11, 12]
                        - percentile: 32
                          data: [9, 10, 11]
                      asset_management_result: [7, 8, 9, 10]
                      reserve_total_amount: 100000
                      withdrawal_total_amount: 100000
                      starts_at: '2020-04-01T00:00:00.000Z'
                      completed_at: '2024-05-06T00:00:00.000Z'
                      created_at: '2021-06-01T00:00:00.000Z'
                      initial_investment: 4000000
                      asset_management_period_years: 30
                      asset_management_period_months: 0
                      reserve_start_year: 2021
                      reserve_start_month: 8
                      reserve_period_years: 25
                      reserve_period_months: 0
                      withdrawal_start_year: 2037
                      withdrawal_start_month: 6
                      withdrawal_period_years: 20
                      withdrawal_period_months: 0
                      withdrawal_frequency: 'monthly'
                      withdrawal_amount: 360000
                      risk_level: 3
                      application_fa_name: 田中 太郎
                      application_date: 2020-04-01T00:00:00.000Z
                      funds_source: '預貯金'
                      percentage_in_financial_assets_over: 30
                      percentage_in_financial_assets_under: 50
                      reserve_monthly_amount: null
                      bonus_months: []
                      increased_amount_at_bonus: null
                      fluctuation_funds_type: null
                      fluctuation_funds_amount: null
                      spot_invest_date: null
                      part_cancel_invest_date: null
                      fund_url: 'https://www.multi-tenant.co.jp/fund/funddetail.php?t=2&fundcd=180361#fundinfo'
                      current_price: 103000
                      first_achievement_probability: 78
                      contract_method: 'pdf_contract'
                      application_status: 'waiting_for_application'
                    revised: null
                    contract_status: 'on_contract_application'
                    invalid_application_reason: null
                    contract_class: 1
                    new_nisa: '1'
                    current_price_detail:
                      current_price_sum: 30000
                      nisa_amount: 10000
                      taxable_amount: 20000
                運用プランが存在しない場合:
                  value:
                    goal_type: 'donation'
                    made:
                      plan_type: ''
                      name: '寄付がしたいから'
                      goal_amount: null
                      calculated_goal_amount: null
                      achievement_probability: null
                      future_return: []
                      asset_management_result: []
                      reserve_total_amount: null
                      withdrawal_total_amount: null
                      starts_at: ''
                      completed_at: ''
                      created_at: '2022-08-24T15:33:44.145Z'
                      initial_investment: null
                      asset_management_period_years: null
                      asset_management_period_months: null
                      reserve_start_year: null
                      reserve_start_month: null
                      reserve_period_years: null
                      reserve_period_months: null
                      withdrawal_start_year: null
                      withdrawal_start_month: null
                      withdrawal_period_years: null
                      withdrawal_period_months: null
                      withdrawal_frequency: ''
                      withdrawal_amount: null
                      risk_level: null
                      application_fa_name: null
                      application_date: null
                      funds_source: null
                      percentage_in_financial_assets_over: null
                      percentage_in_financial_assets_under: null
                      reserve_monthly_amount: null
                      bonus_months: null
                      increased_amount_at_bonus: null
                      fluctuation_funds_type: null
                      fluctuation_funds_amount: null
                      spot_invest_date: null
                      part_cancel_invest_date: null
                      fund_url: null
                      current_price: null
                      first_achievement_probability: null
                      contract_method: null
                      application_status: null
                    revised: null
                    contract_status: 'before_contract'
                    invalid_application_reason: null
                    contract_class: null
                    new_nisa: '2'
                    current_price_detail:
                      current_price_sum: null
        '400':
          $ref: '../afs-client.yaml#/components/responses/BadRequestResponse'
        '403':
          $ref: '../afs-client.yaml#/components/responses/ForbiddenResponse'
        '404':
          $ref: '../afs-client.yaml#/components/responses/FaCustomerGoalNotFoundResponse'
        '500':
          $ref: '../afs-client.yaml#/components/responses/InternalServerErrorResponse'
        '503':
          $ref: '../afs-client.yaml#/components/responses/ServiceUnavailableResponse'
  '/goals/{goal_id}/available-plans':
    parameters:
      - $ref: '../afs-client.yaml#/components/parameters/GoalId'
    get:
      summary: 利用可能な運用プランの取得。
      description: |
        利用できる運用プランを返却する
      tags:
        - 運用プラン
      operationId: get-goals-goal-id-available-plans
      security:
        - Branch/Fa: []
      responses:
        '200':
          description: |
            利用可能な運用プラン。
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AvailablePlanResponse'
              examples:
                テナント設定が全てのプラン使用可能:
                  value:
                    available_plans:
                      - type: 'deferral'
                        is_available: true
                      - type: 'deferral-withdrawal'
                        is_available: true
                      - type: 'reserve'
                        is_available: true
                      - type: 'reserve-deferral-withdrawal'
                        is_available: true
                テナント設定で据置・引出が使用不可:
                  value:
                    available_plans:
                      - type: 'deferral'
                        is_available: true
                      - type: 'reserve'
                        is_available: true
                      - type: 'reserve-deferral-withdrawal'
                        is_available: true
                テナント設定で据置が使用不可:
                  value:
                    available_plans:
                      - type: 'deferral-withdrawal'
                        is_available: true
                      - type: 'reserve'
                        is_available: true
                      - type: 'reserve-deferral-withdrawal'
                        is_available: true
                テナント設定で積立が使用不可:
                  value:
                    available_plans:
                      - type: 'deferral'
                        is_available: true
                      - type: 'deferral-withdrawal'
                        is_available: true
                      - type: 'reserve-deferral-withdrawal'
                        is_available: true
                テナント設定で積立・据置・引出が使用不可:
                  value:
                    available_plans:
                      - type: 'deferral'
                        is_available: true
                      - type: 'deferral-withdrawal'
                        is_available: true
                      - type: 'reserve'
                        is_available: true
        '400':
          $ref: '../afs-client.yaml#/components/responses/BadRequestResponse'
        '401':
          $ref: '../afs-client.yaml#/components/responses/UnauthorizedResponse'
        '403':
          $ref: '../afs-client.yaml#/components/responses/ForbiddenResponse'
        '404':
          $ref: '../afs-client.yaml#/components/responses/FaCustomerGoalNotFoundResponse'
        '500':
          $ref: '../afs-client.yaml#/components/responses/InternalServerErrorResponse'
        '503':
          $ref: '../afs-client.yaml#/components/responses/ServiceUnavailableResponse'

components:
  schemas:
    GoalAssetManagementPlanDetailResponse:
      type: object
      properties:
        plan_type:
          $ref: '../afs-client.yaml#/components/schemas/PlanType'
        name:
          $ref: '../afs-client.yaml#/components/schemas/GoalName'
        goal_amount:
          allOf:
            - $ref: '../afs-client.yaml#/components/schemas/GoalAmount'
            - default: null
        achievement_probability:
          allOf:
            - $ref: '../afs-client.yaml#/components/schemas/AchievementProbability'
            - default: null
            - nullable: true
        future_return:
          allOf:
            - $ref: '../afs-client.yaml#/components/schemas/FutureReturn'
            - default: []
        future_estimation:
          allOf:
            - $ref: '../afs-client.yaml#/components/schemas/FutureReturn'
            - default: []
        asset_management_result:
          allOf:
            - $ref: '../afs-client.yaml#/components/schemas/AssetManagementResult'
            - default: []
        starts_at:
          allOf:
            - $ref: '../afs-client.yaml#/components/schemas/AssetManagementPlanStartsAt'
            - default: '""'
        completed_at:
          allOf:
            - $ref: '../afs-client.yaml#/components/schemas/GoalCompletedAt'
            - default: '""'
        created_at:
          $ref: '../afs-client.yaml#/components/schemas/GoalCreatedAt'
        initial_investment:
          allOf:
            - $ref: '../afs-client.yaml#/components/schemas/InitialInvestment'
            - default: null
        asset_management_period_years:
          allOf:
            - $ref: '../afs-client.yaml#/components/schemas/AssetManagementPeriodYears'
            - default: null
        asset_management_period_months:
          allOf:
            - $ref: '../afs-client.yaml#/components/schemas/AssetManagementPeriodMonths'
            - default: null
        reserve_start_year:
          allOf:
            - $ref: '../afs-client.yaml#/components/schemas/ReserveStartYear'
            - default: null
        reserve_start_month:
          allOf:
            - $ref: '../afs-client.yaml#/components/schemas/ReserveStartMonth'
            - default: null
        reserve_period_years:
          allOf:
            - $ref: '../afs-client.yaml#/components/schemas/ReservePeriodYears'
            - default: null
        reserve_period_months:
          allOf:
            - $ref: '../afs-client.yaml#/components/schemas/ReservePeriodMonths'
            - default: null
        withdrawal_start_year:
          allOf:
            - $ref: '../afs-client.yaml#/components/schemas/WithdrawalStartYear'
            - default: null
        withdrawal_start_month:
          allOf:
            - $ref: '../afs-client.yaml#/components/schemas/WithdrawalStartMonth'
            - default: null
        withdrawal_period_years:
          allOf:
            - $ref: '../afs-client.yaml#/components/schemas/WithdrawalPeriodYears'
            - default: null
        withdrawal_period_months:
          allOf:
            - $ref: '../afs-client.yaml#/components/schemas/WithdrawalPeriodMonths'
            - default: null
        withdrawal_frequency:
          allOf:
            - $ref: '../afs-client.yaml#/components/schemas/WithdrawalFrequency'
            - default: '""'
        withdrawal_amount:
          allOf:
            - $ref: '../afs-client.yaml#/components/schemas/WithdrawalAmount'
            - default: null
        risk_level:
          $ref: '../afs-client.yaml#/components/schemas/RiskLevel'
        application_fa_name:
          $ref: '../afs-client.yaml#/components/schemas/FaName'
        application_date:
          $ref: '../afs-client.yaml#/components/schemas/ApplicationDate'
        funds_source:
          allOf:
            - $ref: '../afs-client.yaml#/components/schemas/FundsSource'
            - default: null
        percentage_in_financial_assets_over:
          $ref: '../afs-client.yaml#/components/schemas/PercentageInFinancialAssetsOver'
        percentage_in_financial_assets_under:
          $ref: '../afs-client.yaml#/components/schemas/PercentageInFinancialAssetsUnder'
        reserve_monthly_amount:
          allOf:
            - $ref: '../afs-client.yaml#/components/schemas/ReserveMonthlyAmount'
            - default: null
        bonus_months:
          allOf:
            - $ref: '../afs-client.yaml#/components/schemas/BonusMonths'
            - default: []
        increased_amount_at_bonus:
          allOf:
            - $ref: '../afs-client.yaml#/components/schemas/IncreasedAmountAtBonus'
            - default: null
        fluctuation_funds_type:
          allOf:
            - $ref: '../afs-client.yaml#/components/schemas/FluctuationFundsType'
            - default: null
        fluctuation_funds_amount:
          allOf:
            - $ref: '../afs-client.yaml#/components/schemas/FluctuationFundsAmount'
            - default: null
        spot_invest_date:
          allOf:
            - $ref: '../afs-client.yaml#/components/schemas/SpotInvestDate'
            - default: null
        part_cancel_invest_date:
          allOf:
            - $ref: '../afs-client.yaml#/components/schemas/PartCancelInvestDate'
            - default: null
        fund_url:
          allOf:
            - $ref: '../afs-client.yaml#/components/schemas/FundUrl'
            - default: null
        current_price:
          allOf:
            - $ref: '../afs-client.yaml#/components/schemas/CurrentPrice'
            - default: null
        first_achievement_probability:
          allOf:
            - $ref: '../afs-client.yaml#/components/schemas/FirstAchievementProbability'
            - default: null
        contract_method:
          allOf:
            - $ref: '../afs-client.yaml#/components/schemas/contractMethod'
            - default: null
    AssetManagementPlanDetailResponse:
      type: object
      required:
        - goal_type
        - made
        - revised
        - contract_status
        - invalid_application_reason
        - contract_class
      properties:
        goal_type:
          $ref: '../afs-client.yaml#/components/schemas/GoalType'
        made:
          allOf:
            - $ref: '#/components/schemas/GoalAssetManagementPlanDetailResponse'
            - description: |
                見直し中以外の状態のデータ。
            - required:
                - plan_type
                - name
                - goal_amount
                - achievement_probability
                - future_return
                - future_estimation
                - asset_management_result
                - starts_at
                - completed_at
                - created_at
                - initial_investment
                - asset_management_period_years
                - asset_management_period_months
                - reserve_start_year
                - reserve_start_month
                - reserve_period_years
                - reserve_period_months
                - withdrawal_start_year
                - withdrawal_start_month
                - withdrawal_period_years
                - withdrawal_period_months
                - withdrawal_frequency
                - withdrawal_amount
                - risk_level
                - application_fa_name
                - application_date
                - funds_source
                - percentage_in_financial_assets_over
                - percentage_in_financial_assets_under
                - reserve_monthly_amount
                - bonus_months
                - increased_amount_at_bonus
                - contract_method
        revised:
          allOf:
            - $ref: '#/components/schemas/GoalAssetManagementPlanDetailResponse'
            - description: |
                見直し中のデータ。
        contract_status:
          $ref: '../afs-client.yaml#/components/schemas/ContractStatus'
        invalid_application_reason:
          allOf:
            - $ref: '../afs-client.yaml#/components/schemas/InvalidApplicationReason'
            - default: null
        contract_class:
          allOf:
            - $ref: '../afs-client.yaml#/components/schemas/ContractClass'
            - default: null

    AvailablePlanResponse:
      type: object
      required:
        - available_plans
      properties:
        available_plans:
          type: array
          items:
            type: object
            required:
              - type
              - is_available
            properties:
              type:
                $ref: '../afs-client.yaml#/components/schemas/PlanType'
              is_available:
                $ref: '#/components/schemas/IsPlanAvailable'

      description: |
        運用プランが選択できるかどうかを返却する配列。
        配列に要素が含まれないプランは、テナント固有設定により元々選択ができないことを表す。

    IsPlanAvailable:
      type: boolean
      description: 運用プランが選択可能かどうかを返却する
